version: '3.5'
services:
  chimer-dev:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./src:/app/src
